<?php
// index.php — Homepage
require_once __DIR__ . '/includes/bootstrap.php';

// Generate initial address (US by default)
$defaultCountry = 'us';
$initialAddress = AddressGenerator::generate($defaultCountry);
AddressGenerator::log($initialAddress);

// Fetch content sections (ordered)
$stmt = get_db()->query('SELECT * FROM content_sections WHERE is_active = 1 ORDER BY sort_order ASC');
$contentSections = $stmt->fetchAll();

// Fetch 5 latest published posts for blog preview
$stmt = get_db()->query(
    'SELECT p.*, c.name AS category_name
     FROM posts p
     LEFT JOIN categories c ON c.id = p.category_id
     WHERE p.status = "published"
     ORDER BY p.published_at DESC LIMIT 5'
);
$latestPosts = $stmt->fetchAll();

// Fetch featured posts for sidebar
$stmt = get_db()->prepare(
    'SELECT id, title, slug, thumbnail FROM posts
     WHERE is_featured = 1 AND status = "published"
     ORDER BY published_at DESC LIMIT 5'
);
$stmt->execute();
$featuredPosts = $stmt->fetchAll();

// SEO
$pageTitle    = get_setting('site_name', 'Fake Address Generator') . ' - Generate Realistic Fake Addresses';
$metaDesc     = 'Generate highly realistic fake addresses for software testing, privacy protection, and data masking. Supports US, UK, Canada, Australia, Germany, and Japan.';
$metaKeywords = 'fake address generator, random address generator, dummy address, test data, fake US address, fake UK address';

require_once __DIR__ . '/templates/header.php';
?>

<section class="hero">
  <h1>Random Fake Address Generator</h1>
  <p>Generate highly realistic, random addresses for software testing, privacy protection, and data masking.</p>
</section>

<div class="main-layout">

  <!-- PRIMARY CONTENT -->
  <div class="primary-content">

    <!-- Address Generator Widget -->
    <?php require __DIR__ . '/templates/generator_widget.php'; ?>

    <!-- Dynamic Content Sections -->
    <?php foreach ($contentSections as $section): ?>
      <section class="content-section">
        <h2><?= e($section['title']) ?></h2>
        <?= $section['content']?>
      </section>
    <?php endforeach; ?>

    <!-- FAQ Section -->
    <section class="faq-section">
      <h2>Frequently Asked Questions</h2>
      <div class="accordion">

        <div class="accordion-item">
          <input type="checkbox" id="faq1" class="accordion-input">
          <label for="faq1" class="accordion-label">What is a Fake Address Generator used for?</label>
          <div class="accordion-content">
            <p>A fake address generator is primarily used by developers and QA testers to fill registration forms, test shipping APIs, and generate realistic dummy datasets without using real personal information. It's also useful for writers, game designers, and privacy-conscious users who don't want to share their real location with non-essential websites.</p>
          </div>
        </div>

        <div class="accordion-item">
          <input type="checkbox" id="faq2" class="accordion-input">
          <label for="faq2" class="accordion-label">Are these addresses real?</label>
          <div class="accordion-content">
            <p>No. All addresses generated by this tool are entirely fictional and randomly constructed. They are not tied to any real person, property, or postal record. Street names, ZIP codes, and phone numbers follow realistic formatting but do not correspond to actual locations or people.</p>
          </div>
        </div>

        <div class="accordion-item">
          <input type="checkbox" id="faq3" class="accordion-input">
          <label for="faq3" class="accordion-label">Is it legal to use fake addresses?</label>
          <div class="accordion-content">
            <p>Using fake addresses for software testing, data masking, form validation, and similar technical purposes is entirely legal. However, you should never use fake addresses to deceive others, commit fraud, or violate a platform's terms of service. Always use this tool responsibly and ethically.</p>
          </div>
        </div>

        <div class="accordion-item">
          <input type="checkbox" id="faq4" class="accordion-input">
          <label for="faq4" class="accordion-label">Which countries are supported?</label>
          <div class="accordion-content">
            <p>We currently support the United States, United Kingdom, Canada, Australia, Germany, and Japan. Each country uses real city names, authentic street name styles, and correctly formatted postal codes. We are actively working to add more countries.</p>
          </div>
        </div>

        <div class="accordion-item">
          <input type="checkbox" id="faq5" class="accordion-input">
          <label for="faq5" class="accordion-label">Can I filter by state or gender?</label>
          <div class="accordion-content">
            <p>Yes. Use the <strong>Custom Generation</strong> panel in the sidebar to select a specific state/region and choose a gender (Male, Female, or Random). Click <em>Apply &amp; Generate</em> to generate an address with your chosen parameters.</p>
          </div>
        </div>

      </div>
    </section>

    <!-- Blog Preview Section -->
    <?php if (!empty($latestPosts)): ?>
    <section class="content-section">
      <h2>Latest Guides &amp; Articles</h2>
      <div class="blog-grid">
        <?php foreach ($latestPosts as $post): ?>
          <article class="blog-card">
            <?php if ($post['thumbnail']): ?>
            <div class="blog-card-thumb">
              <a href="<?= BASE_URL ?>/blog/<?= e($post['slug']) ?>">
                <img src="<?= BASE_URL . '/' . e($post['thumbnail']) ?>" alt="<?= e($post['title']) ?>" loading="lazy">
              </a>
            </div>
            <?php endif; ?>
            <div class="blog-card-body">
              <?php if ($post['category_name']): ?>
                <span class="blog-card-cat"><?= e($post['category_name']) ?></span>
              <?php endif; ?>
              <h3 class="blog-card-title">
                <a href="<?= BASE_URL ?>/blog/<?= e($post['slug']) ?>"><?= e($post['title']) ?></a>
              </h3>
              <p class="blog-card-excerpt"><?= e($post['excerpt'] ?: excerpt($post['content'])) ?></p>
              <div class="blog-card-meta">
                <span><?= fmt_date($post['published_at'] ?? $post['created_at']) ?></span>
                <span><?= (int)$post['views'] ?> views</span>
              </div>
            </div>
          </article>
        <?php endforeach; ?>
      </div>
      <div class="text-center">
        <a href="<?= BASE_URL ?>/blog" class="btn btn-outline">View All Articles →</a>
      </div>
    </section>
    <?php endif; ?>

  </div><!-- /primary-content -->

  <!-- SIDEBAR -->
  <?php require __DIR__ . '/templates/sidebar.php'; ?>

</div><!-- /main-layout -->

<?php require __DIR__ . '/templates/footer.php'; ?>
